site_name: bm-templ-project
site_description: <set:docs-site-description>
# site_url: <set:docs-site-url>
repo_name: <set:repo-name>
# repo_url: <set:repo-url>
theme:
  name: material
watch:
  - bm_templ_project
plugins:
  - mkdocstrings
  - search
  - autorefs
nav:
  - index.md
  - examples.md
  - Code Reference:
      - reactor.py: reference/bm_templ_project.reactor.md
