name: template_ci

on:
  schedule:
    # Runs on a Monday at 7.05
    - cron: "5 7 * * 1"
  pull_request:
  push:
    branches:
      - develop
      - main

env:
  python-version: "3.12"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup python and hatch
        uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@main
        with:
          python-version: ${{ env.python-version }}

      - name: Setup dummy git credententials
        shell: bash -l {0}
        run: |
          git config user.name ci
          git config user.email ci

      - name: run cookiecutter
        shell: bash -l {0}
        run: |
          # take default options for cookecutter and answer yes to git post_gen question
          # pip/uv is available
          bash scripts/setup_repo.sh -d <<< $'y'

      - name: Run Hatch linting tasks
        uses: Fusion-Power-Plant-Framework/fppf-actions/hatch-lint@main

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup dummy git credententials
        shell: bash -l {0}
        run: |
          git config user.name ci
          git config user.email ci

      - name: run cookiecutter
        shell: bash -l {0}
        run: |
          # take default options for cookecutter and answer yes to git post_gen question
          # pip/uv is available
          bash scripts/setup_repo.sh -d <<< $'y'

      - name: Build bluemira
        uses: Fusion-Power-Plant-Framework/fppf-actions/build-action@deddef408d0061e542692a7bf97368449c5ee5b3
        with:
          python-version: ${{ env.python-version }}
          clone-bluemira: "true"

      - name: Run pytest
        shell: bash -l {0}
        env:
          PACKAGE: template_project
        run: |
          pytest --cov=${PACKAGE} \
                 --cov-report html:htmlcov \
                 --cov-report xml \
                 --json-report \
                 --json-report-indent=3 \
                 tests
